import { Bot, Cpu, Sparkles } from "lucide-react";

export const MODELS = [
    { id: "claude-large", name: "Claude Opus 4.5", icon: Bot, color: "text-claude-accent", desc: "Advanced reasoning & vision" },
    { id: "deepseek", name: "DeepSeek V3.2", icon: Cpu, color: "text-blue-500", desc: "Powerful code and logic" },
    { id: "openai-large", name: "GPT-5.2", icon: Sparkles, color: "text-green-500", desc: "Versatile and creative" },
];

export const TRANSLATIONS = {
    en: {
        newChat: "New Session",
        searchHistory: "Search index...",
        conversations: "Stored Sessions",
        noChats: "No active sessions",
        changeModel: "Select Model",
        pollenBalance: "API Credits",
        updateBalance: "Sync balance",
        dropFiles: "Upload source for analysis",
        helloMessage: "Querying",
        dropInstruction: "Upload documents or enter technical queries below.",
        placeholder: "Enter instruction for {model}...",
        stopGeneration: "Abort generation",
        loadingPdf: "Extracting structural data from PDF... Please wait.",
        deleteConfirm: "Confirm session deletion?",
        logoutConfirm: "Close session and reset API credentials?",
        logoutBtn: "Reset Session",
        configTitle: "System Authentication",
        configDesc: "Provide a Pollinations API Key to initialize a secure analytical session. Required: `claude-large` (Opus 4.5), `deepseek` (V3), and `openai-large` (ChatGPT 5.2).",
        configPlaceholder: "API Key (sk_...)",
        configBtn: "Initialize",
        getApiKey: "Credential Management",
        errorApiKey: "Invalid API Key format.",
        language: "Locale",
        spanish: "ES",
        english: "EN",
        initialGreeting: "System ready. Awaiting document input for structural analysis.",
        seeReasoning: "Show logic",
        hideReasoning: "Hide logic"
    },
    es: {
        newChat: "Nueva Sesión",
        searchHistory: "Buscar en el índice...",
        conversations: "Sesiones Guardadas",
        noChats: "Sin sesiones activas",
        changeModel: "Seleccionar Modelo",
        pollenBalance: "Créditos API",
        updateBalance: "Sincronizar saldo",
        dropFiles: "Subir archivo para análisis",
        helloMessage: "Consultando",
        dropInstruction: "Sube documentos o ingresa consultas técnicas abajo.",
        placeholder: "Instrucción para {model}...",
        stopGeneration: "Abortar generación",
        loadingPdf: "Extrayendo datos estructurales del PDF... Por favor espere.",
        deleteConfirm: "¿Confirmar eliminación de sesión?",
        logoutConfirm: "¿Cerrar sesión y reiniciar credenciales?",
        logoutBtn: "Reiniciar Sesión",
        configTitle: "Autenticación del Sistema",
        configDesc: "Ingrese su API Key de Pollinations para iniciar la sesión segura. Requerido: `claude-large` (Opus), `deepseek` (V3) e `openai-large` (ChatGPT).",
        configPlaceholder: "API Key (sk_...)",
        configBtn: "Inicializar",
        getApiKey: "Gestión de Credenciales",
        errorApiKey: "Formato de clave inválido.",
        language: "Localización",
        spanish: "ES",
        english: "EN",
        initialGreeting: "Sistema listo. Esperando documentos para análisis estructural.",
        seeReasoning: "Ver lógica",
        hideReasoning: "Ocultar lógica"
    }
};
